appearance_thresh: 0.25
cmc_method: sparseOptFlow
conf: 0.42266880177138644
conf_thresh: 0.590780763917436
cov_alpha: 90
frame_rate: 30
match_thresh: 0.8
new_track_thresh: 0.1
proximity_thresh: 0.6
tent_conf_thresh: 0.7
track_buffer: 30
track_high_thresh: 0.6
track_low_thresh: 0.2